# Site settings
title: Harvey | 前端学习
description: "Harvey's blog build with Jekyll."
url: "http://hewei.site"
author:
  name: "Harvey"
  email: "heweimr@gmail.com"
  url: "http://www.hewei.site"

# Build settings
baseurl: '/' # Change this to your relative path (ex: /blog/), or leave just a /
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: true
reverse: false

# 首页摘要
excerpt_separator: <!--more-->
